# 服务端口 一般是 80 的，但 80 容易被占用
server:
  port: 80
  # 服务名
spring:
  application:
    name: service-gateway

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-hosp  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-hosp #设置路由的uri，lb 是使用loadbalance 默认轮询
          predicates:
            - Path=/*/hosp/** #设置路由断言,代理servicerId为auth-service的/auth/路径
        # 数据字典模块
        - id: service-cmn  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-cmn #设置路由的uri
          predicates:
            - Path=/*/cmn/** #设置路由断言,代理servicerId为auth-service的/auth/路径
        # 用户模块
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        # 发送邮箱验证码
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/*/msm/**
        # 发送邮箱验证码
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        # 发送邮箱验证码
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        # 发送邮箱验证码
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/*/statistics/**